# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/cui-jwt-quarkus-parent/cui-jwt-quarkus-integration-tests"
    schedule:
      interval: "weekly"
    # Note: This tracks Dockerfiles only. For docker-compose.yml images,
    # manual updates are required as dependabot's Docker ecosystem
    # doesn't scan compose files. Current manual update needed:
    # - quay.io/keycloak/keycloak:26.2.5 in docker-compose.yml

  - package-ecosystem: npm
    directory: "/cui-jwt-quarkus-parent/cui-jwt-quarkus-deployment"
    schedule:
      interval: "weekly"
