name: JMH Benchmark

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags: [ "*" ]
  workflow_dispatch:

# Declare default permissions as read only
permissions: read-all

# Prevent concurrent benchmark runs to avoid interference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress runs as benchmarks are expensive

jobs:
  benchmark:
    name: Run JMH Benchmarks
    runs-on: ubuntu-latest
    # Only run on merged PRs, not just closed ones
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    # Add timeout to prevent long-running jobs
    timeout-minutes: 30
    permissions:
      # Needed to upload artifacts
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build cui-jwt-validation
        run: |
          # Build validation module first to ensure test artifact is available for benchmarking
          ./mvnw --no-transfer-progress clean install -pl cui-jwt-validation -DskipTests

      - name: Run JMH Benchmarks
        run: |
          # Create directory for benchmark results
          mkdir -p benchmark-results

          # Run benchmarks with JSON output format, skipping tests to avoid duplicate runs
          # Configure JMH parameters for CI environment: fewer iterations for faster execution
          ./mvnw --no-transfer-progress clean verify -pl cui-jwt-benchmarking -Dskip.benchmark=false -DskipTests \
            -Djmh.result.format=JSON \
            -Djmh.result.filePrefix=benchmark-results/jmh-result \
            -Djmh.iterations=3 \
            -Djmh.warmupIterations=2 \
            -Djmh.forks=1 \
            -Djmh.threads=2

          # Move benchmark results to expected location for upload
          if [ -d "cui-jwt-benchmarking/benchmark-results" ]; then
            echo "Moving benchmark results to upload location..."
            mv cui-jwt-benchmarking/benchmark-results .
          else
            echo "Creating empty benchmark-results directory..."
            mkdir -p benchmark-results
          fi

          # Add timestamp to results
          echo "{ \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"commit\": \"${{ github.sha }}\" }" > benchmark-results/metadata.json

          # Verify that benchmark results were generated
          echo "Checking for benchmark results..."
          ls -la benchmark-results/
          find . -name "jmh-result*.json" -type f || echo "No JMH result files found anywhere"

      - name: Upload benchmark results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: benchmark-results
          path: benchmark-results/
          retention-days: 90  # Keep results for 90 days

      - name: Prepare GitHub Pages visualization
        run: |
          # Create directory for GitHub Pages
          mkdir -p gh-pages

          # Copy benchmark results to gh-pages directory
          cp -r benchmark-results/* gh-pages/

          # Find and rename the JMH result file for visualization
          # First check if jmh-result.json exists in project root
          if [ -f "jmh-result.json" ]; then
            echo "Using jmh-result.json from project root"
            cp jmh-result.json gh-pages/jmh-result.json
          else
            # Find the result file in benchmark-results directory
            echo "Looking for JMH result files in benchmark-results directory"
            find benchmark-results -name "jmh-result*.json" -type f -exec cp {} gh-pages/jmh-result.json \;
          fi

          # Verify and copy the visualizer template
          if [ ! -f "gh-pages/jmh-result.json" ]; then
            echo "ERROR: No benchmark result file found!"
            exit 1
          fi

          # Copy the JMH Visualizer template
          cp cui-jwt-benchmarking/doc/templates/index-visualizer.html gh-pages/index.html

          # Create benchmark badges BEFORE deployment
          # Create directory for badges
          mkdir -p gh-pages/badges

          # Get current date for badge timestamp
          TIMESTAMP=$(date -u +"%Y-%m-%d")

          # Function to create a badge for a benchmark
          create_badge() {
            local benchmark_name=$1
            local display_name=$2
            local badge_name=$3
            local color=$4

            # Extract benchmark data using jq for reliable JSON parsing
            if [ -f "gh-pages/jmh-result.json" ]; then
              local benchmark_entry=$(jq -r '.[] | select(.benchmark == "'"$benchmark_name"'")' gh-pages/jmh-result.json 2>/dev/null)
              local score=$(echo "$benchmark_entry" | jq -r '.primaryMetric.score' 2>/dev/null || echo "N/A")
              local unit=$(echo "$benchmark_entry" | jq -r '.primaryMetric.scoreUnit' 2>/dev/null || echo "")
              
              echo "Debug: Extracting badge for $benchmark_name: score=$score, unit=$unit"
            else
              echo "Warning: jmh-result.json not found in gh-pages directory"
              local score="N/A"
              local unit=""
            fi

            if [ "$score" != "N/A" ] && [ "$score" != "null" ]; then
              # Convert to appropriate unit and format
              if [[ "$unit" == "us/op" ]]; then
                # Convert microseconds to milliseconds for display
                local score_ms=$(echo "scale=3; $score / 1000" | bc -l)
                local formatted_score=$(printf "%.2f" $score_ms)
                local unit_display="ms"
              elif [[ "$unit" == "ms/op" ]]; then
                local formatted_score=$(printf "%.2f" $score)
                local unit_display="ms"
              elif [[ "$unit" == "ops/s" ]]; then
                # Format ops/s with appropriate scale
                if [ $(echo "$score > 1000" | bc -l) -eq 1 ]; then
                  local score_k=$(echo "scale=1; $score / 1000" | bc -l)
                  local formatted_score=$(printf "%.1f" $score_k)
                  local unit_display="k ops/s"
                else
                  local formatted_score=$(printf "%.0f" $score)
                  local unit_display="ops/s"
                fi
              else
                local formatted_score=$(printf "%.2f" $score)
                local unit_display="$unit"
              fi

              # Create badge JSON - no timestamp for validator badge, include for others
              if [[ "$badge_name" == "validator-badge" ]]; then
                echo "{\"schemaVersion\":1,\"label\":\"$display_name\",\"message\":\"${formatted_score} ${unit_display}\",\"color\":\"$color\"}" > "gh-pages/badges/$badge_name.json"
              else
                echo "{\"schemaVersion\":1,\"label\":\"$display_name\",\"message\":\"${formatted_score} ${unit_display} ($TIMESTAMP)\",\"color\":\"$color\"}" > "gh-pages/badges/$badge_name.json"
              fi

              # Create badge markdown for README
              echo "[![$display_name](https://img.shields.io/endpoint?url=https://cuioss.github.io/cui-jwt/benchmarks/badges/$badge_name.json)](https://cuioss.github.io/cui-jwt/benchmarks/)" >> gh-pages/badge-markdown.txt

              echo "Created badge for $display_name: $formatted_score $unit_display"
            else
              echo "Warning: Could not find benchmark results for $benchmark_name"
              # Create placeholder badge
              echo "{\"schemaVersion\":1,\"label\":\"$display_name\",\"message\":\"No Data\",\"color\":\"red\"}" > "gh-pages/badges/$badge_name.json"
            fi
          }

          # Create header for badge markdown
          echo "## Benchmark Results ($TIMESTAMP)" > gh-pages/badge-markdown.txt

          # Note: Access Token Validation badge removed as redundant with Performance Score
          # The Performance Score badge already includes average time information plus comprehensive metrics

          # Create performance badge using script
          if [ -f "gh-pages/jmh-result.json" ]; then
            bash cui-jwt-benchmarking/doc/templates/scripts/create-performance-badge.sh gh-pages/jmh-result.json gh-pages/badges
          else
            echo "Warning: jmh-result.json not found"
            echo "{\"schemaVersion\":1,\"label\":\"Performance Score\",\"message\":\"No Data\",\"color\":\"red\"}" > "gh-pages/badges/performance-badge.json"
          fi

          # Create a combined badge for all benchmarks
          echo "{\"schemaVersion\":1,\"label\":\"JWT Benchmarks\",\"message\":\"Updated $TIMESTAMP\",\"color\":\"brightgreen\"}" > gh-pages/badges/all-benchmarks.json

          # Create last benchmark run badge
          echo "{\"schemaVersion\":1,\"label\":\"Last Benchmark Run\",\"message\":\"$TIMESTAMP\",\"color\":\"blue\"}" > gh-pages/badges/last-run-badge.json

          # Performance Tracking System using scripts
          echo "Setting up performance tracking..."
          COMMIT_HASH="${{ github.sha }}"
          
          if [ -f "gh-pages/jmh-result.json" ]; then
            # Create performance tracking data using script
            TRACKING_OUTPUT=$(bash cui-jwt-benchmarking/doc/templates/scripts/create-performance-tracking.sh gh-pages/jmh-result.json cui-jwt-benchmarking/doc/templates gh-pages "$COMMIT_HASH" 2>&1)
            echo "$TRACKING_OUTPUT"
            
            # Extract metrics from tracking script output
            PERF_SCORE=$(echo "$TRACKING_OUTPUT" | grep "PERF_SCORE=" | cut -d'=' -f2)
            PERF_THROUGHPUT=$(echo "$TRACKING_OUTPUT" | grep "PERF_THROUGHPUT=" | cut -d'=' -f2)
            PERF_LATENCY=$(echo "$TRACKING_OUTPUT" | grep "PERF_LATENCY=" | cut -d'=' -f2)
            PERF_RESILIENCE=$(echo "$TRACKING_OUTPUT" | grep "PERF_RESILIENCE=" | cut -d'=' -f2)
            
            if [ -n "$PERF_SCORE" ] && [ "$PERF_SCORE" != "0" ]; then
              # Update consolidated tracking and create trend badge using script
              bash cui-jwt-benchmarking/doc/templates/scripts/update-performance-trends.sh cui-jwt-benchmarking/doc/templates gh-pages "$COMMIT_HASH" "$PERF_SCORE" "$PERF_THROUGHPUT" "$PERF_LATENCY" "$PERF_RESILIENCE"
            else
              echo "Warning: Could not extract valid performance metrics for trend tracking"
              echo "{\"schemaVersion\":1,\"label\":\"Performance Trend\",\"message\":\"→ No Data\",\"color\":\"lightgrey\"}" > "gh-pages/badges/trend-badge.json"
            fi
          else
            echo "Warning: jmh-result.json not found for performance tracking"
            echo "{\"schemaVersion\":1,\"label\":\"Performance Trend\",\"message\":\"→ No Data\",\"color\":\"lightgrey\"}" > "gh-pages/badges/trend-badge.json"
          fi

          # Note: validator-badge.json removed as redundant with comprehensive performance-badge.json

      - name: Deploy to cuioss.github.io
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: gh-pages
          repository-name: cuioss/cuioss.github.io
          target-folder: cui-jwt/benchmarks
          branch: main
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
