name: Performance Benchmark

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
  push:
    tags: [ "*" ]
  workflow_dispatch:

# Declare default permissions as read only
permissions: read-all

# Prevent concurrent benchmark runs to avoid interference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress runs as benchmarks are expensive

jobs:
  benchmark:
    name: Run JMH Benchmarks
    runs-on: ubuntu-latest
    # Only run on merged PRs, not just closed ones
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    # Add timeout to prevent long-running jobs (increased for integration benchmarks)
    timeout-minutes: 45
    permissions:
      # Needed to upload artifacts
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build cui-jwt-validation
        run: |
          # Build validation module first to ensure test artifact is available for benchmarking
          ./mvnw --no-transfer-progress clean install -DskipTests

      - name: Run Micro Benchmarks
        run: |
          # Create directory for benchmark results
          mkdir -p benchmark-results

          # Run micro benchmarks using configuration from pom.xml
          ./mvnw --no-transfer-progress clean verify -pl cui-jwt-benchmarking -Pbenchmark

          # Move micro benchmark results to expected location for upload
          if [ -d "cui-jwt-benchmarking/target/benchmark-results" ]; then
            echo "Moving micro benchmark results to upload location..."
            mv cui-jwt-benchmarking/target/benchmark-results/* benchmark-results/ 2>/dev/null || true
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.7.1

      - name: Run Integration Benchmarks
        run: |
          # Run integration benchmarks with native image using profile
          echo "🚀 Running integration benchmarks with native Quarkus..."
          ./mvnw --no-transfer-progress clean verify -pl cui-jwt-quarkus-parent/quarkus-integration-benchmark -Pbenchmark-testing -DskipTests

          # Move integration benchmark results to expected location for upload
          if [ -d "cui-jwt-quarkus-parent/quarkus-integration-benchmark/target/benchmark-results" ]; then
            echo "Moving integration benchmark results to upload location..."
            # Copy health check and JWT validation results
            cp cui-jwt-quarkus-parent/quarkus-integration-benchmark/target/benchmark-results/health-check-results.json benchmark-results/ 2>/dev/null || echo "No health check results"
            cp cui-jwt-quarkus-parent/quarkus-integration-benchmark/target/benchmark-results/jwt-validation-results.json benchmark-results/ 2>/dev/null || echo "No JWT validation results"
          fi

          # Add timestamp to results
          echo "{ \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"commit\": \"${{ github.sha }}\" }" > benchmark-results/metadata.json

          # Verify that benchmark results were generated
          echo "Checking for benchmark results..."
          ls -la benchmark-results/
          find . -name "*benchmark-result*.json" -type f || echo "No benchmark result files found anywhere"

      - name: Upload benchmark results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: benchmark-results
          path: benchmark-results/
          retention-days: 90  # Keep results for 90 days

      - name: Prepare GitHub Pages visualization
        run: |
          # Get current date for badge timestamp in Berlin time
          TIMESTAMP=$(TZ='Europe/Berlin' date +"%Y-%m-%d")
          TIMESTAMP_WITH_TIME=$(TZ='Europe/Berlin' date +"%Y-%m-%d %H:%M %Z")

          # Create gh-pages directory
          mkdir -p gh-pages

          # Create header for badge markdown
          echo "## Benchmark Results ($TIMESTAMP)" > gh-pages/badge-markdown.txt

          # Process micro benchmarks (legacy jmh-result.json for compatibility)
          if [ -f "benchmark-results/micro-benchmark-result.json" ]; then
            echo "Processing micro benchmark results..."
            # Copy for legacy compatibility
            cp benchmark-results/micro-benchmark-result.json benchmark-results/jmh-result.json

            # Prepare GitHub Pages structure using script for micro benchmarks
            bash cui-jwt-benchmarking/scripts/prepare-github-pages.sh benchmark-results cui-jwt-benchmarking/doc/templates gh-pages

            # Create performance badge using unified script for micro benchmarks
            bash cui-jwt-benchmarking/scripts/create-unified-performance-badge.sh micro gh-pages/jmh-result.json gh-pages/badges

            # Create simple badges using script for micro benchmarks
            bash cui-jwt-benchmarking/scripts/create-simple-badge.sh gh-pages/jmh-result.json gh-pages/badges "$TIMESTAMP" "$TIMESTAMP_WITH_TIME"

            # Performance Tracking System for micro benchmarks
            echo "Setting up micro benchmark performance tracking..."
            COMMIT_HASH="${{ github.sha }}"

            # Create performance tracking data using script
            TRACKING_OUTPUT=$(bash cui-jwt-benchmarking/scripts/create-performance-tracking.sh gh-pages/jmh-result.json cui-jwt-benchmarking/doc/templates gh-pages "$COMMIT_HASH" 2>&1)
            echo "$TRACKING_OUTPUT"

            # Extract metrics from tracking script output
            PERF_SCORE=$(echo "$TRACKING_OUTPUT" | grep "PERF_SCORE=" | cut -d'=' -f2)
            PERF_THROUGHPUT=$(echo "$TRACKING_OUTPUT" | grep "PERF_THROUGHPUT=" | cut -d'=' -f2)
            PERF_LATENCY=$(echo "$TRACKING_OUTPUT" | grep "PERF_LATENCY=" | cut -d'=' -f2)
            PERF_RESILIENCE=$(echo "$TRACKING_OUTPUT" | grep "PERF_RESILIENCE=" | cut -d'=' -f2)

            if [ -n "$PERF_SCORE" ] && [ "$PERF_SCORE" != "0" ]; then
              # Update consolidated tracking and create trend badge using script
              bash cui-jwt-benchmarking/scripts/update-performance-trends.sh cui-jwt-benchmarking/doc/templates gh-pages "$COMMIT_HASH" "$PERF_SCORE" "$PERF_THROUGHPUT" "$PERF_LATENCY" "$PERF_RESILIENCE"
            else
              echo "Warning: Could not extract valid performance metrics for trend tracking"
              echo "{\"schemaVersion\":1,\"label\":\"Performance Trend\",\"message\":\"→ No Data\",\"color\":\"lightgrey\"}" > "gh-pages/badges/trend-badge.json"
            fi
          else
            echo "Warning: micro-benchmark-result.json not found"
            echo "{\"schemaVersion\":1,\"label\":\"Performance Score\",\"message\":\"No Data\",\"color\":\"red\"}" > "gh-pages/badges/performance-badge.json"
            echo "{\"schemaVersion\":1,\"label\":\"Performance Trend\",\"message\":\"→ No Data\",\"color\":\"lightgrey\"}" > "gh-pages/badges/trend-badge.json"
          fi

          # Process integration benchmarks (new structure with two files)
          if [ -f "benchmark-results/health-check-results.json" ] && [ -f "benchmark-results/jwt-validation-results.json" ]; then
            echo "Processing integration benchmark results..."

            # Create combined integration results file for compatibility
            jq -n --slurpfile health benchmark-results/health-check-results.json --slurpfile jwt benchmark-results/jwt-validation-results.json '
              {
                "timestamp": (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
                "commit": "${{ github.sha }}",
                "health_check": $health[0],
                "jwt_validation": $jwt[0],
                "jwt_overhead_ms": ($jwt[0].latency_p95_ms - $health[0].latency_p95_ms)
              }' > benchmark-results/integration-benchmark-result.json

            # Copy integration results to unified data location
            cp benchmark-results/integration-benchmark-result.json gh-pages/data/integration-result.json

            # Copy integration template to unified structure
            cp cui-jwt-benchmarking/doc/templates/integration-index.html gh-pages/integration-index.html

            # Extract metrics from new structure
            HEALTH_LATENCY=$(jq -r '.health_check.latency_p95_ms' benchmark-results/integration-benchmark-result.json)
            JWT_LATENCY=$(jq -r '.jwt_validation.latency_p95_ms' benchmark-results/integration-benchmark-result.json)
            JWT_THROUGHPUT=$(jq -r '.jwt_validation.throughput_rps' benchmark-results/integration-benchmark-result.json)
            JWT_OVERHEAD=$(jq -r '.jwt_overhead_ms' benchmark-results/integration-benchmark-result.json)

            echo "Integration Performance Metrics:"
            echo "  Health Check P95: ${HEALTH_LATENCY}ms"
            echo "  JWT Validation P95: ${JWT_LATENCY}ms"
            echo "  JWT Throughput: ${JWT_THROUGHPUT} ops/s"
            echo "  JWT Overhead: ${JWT_OVERHEAD}ms"

            # Create integration performance badges in unified badges directory
            echo "{\"schemaVersion\":1,\"label\":\"JWT P95 Latency\",\"message\":\"${JWT_LATENCY}ms\",\"color\":\"blue\"}" > "gh-pages/badges/integration-performance-badge.json"
            echo "{\"schemaVersion\":1,\"label\":\"JWT Throughput\",\"message\":\"${JWT_THROUGHPUT} ops/s\",\"color\":\"green\"}" > "gh-pages/badges/integration-throughput-badge.json"
            echo "{\"schemaVersion\":1,\"label\":\"JWT Overhead\",\"message\":\"${JWT_OVERHEAD}ms\",\"color\":\"orange\"}" > "gh-pages/badges/integration-overhead-badge.json"

            # Add integration benchmark link to main page
            echo "- [Integration Benchmark Results](integration-index.html)" >> gh-pages/badge-markdown.txt
          else
            echo "Warning: health-check-results.json or jwt-validation-results.json not found"
            echo "{\"schemaVersion\":1,\"label\":\"Integration Performance\",\"message\":\"No Data\",\"color\":\"red\"}" > "gh-pages/badges/integration-performance-badge.json"
            echo "{\"schemaVersion\":1,\"label\":\"Integration Trend\",\"message\":\"→ No Data\",\"color\":\"lightgrey\"}" > "gh-pages/badges/integration-trend-badge.json"
          fi

      - name: Deploy to cuioss.github.io
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: gh-pages
          repository-name: cuioss/cuioss.github.io
          target-folder: cui-jwt/benchmarks
          branch: main
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
