name: Performance Benchmark

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
  push:
    tags: [ "*" ]
  workflow_dispatch:

# Declare default permissions as read only
permissions: read-all

# Prevent concurrent benchmark runs to avoid interference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress runs as benchmarks are expensive

jobs:
  benchmark:
    name: Run JMH Benchmarks
    runs-on: ubuntu-latest
    # Only run on merged PRs, not just closed ones
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    # Add timeout to prevent long-running jobs (increased for integration benchmarks)
    timeout-minutes: 45
    permissions:
      # Needed to upload artifacts
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache npm packages
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build cui-jwt-validation
        run: |
          # Build validation module first to ensure test artifact is available for benchmarking
          ./mvnw --no-transfer-progress clean install -DskipTests

      - name: Run Micro Benchmarks
        run: |
          # Run micro benchmarks using configuration from pom.xml
          # The benchmarks now automatically generate artifacts in target/benchmark-results
          ./mvnw --no-transfer-progress clean verify -pl benchmarking/benchmark-library -Pbenchmark
          
          # Verify artifacts were generated
          echo "📊 Micro benchmark artifacts generated:"
          ls -la benchmarking/benchmark-library/target/benchmark-results/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.7.1

      - name: Run Integration Benchmarks
        run: |
          # Run integration benchmarks with native image using profile that includes container startup
          # The benchmarks now automatically generate artifacts in target/benchmark-results
          echo "🚀 Running integration benchmarks with native Quarkus..."
          ./mvnw --no-transfer-progress clean verify -pl benchmarking/benchmark-integration-quarkus -Pbenchmark
          
          # Verify artifacts were generated
          echo "📊 Integration benchmark artifacts generated:"
          ls -la benchmarking/benchmark-integration-quarkus/target/benchmark-results/

      - name: Archive Historical Data
        run: |
          # Generate timestamp and commit info
          TIMESTAMP=$(date -u +"%Y-%m-%d-T%H%MZ")
          COMMIT_SHA="${{ github.sha }}"
          ARCHIVE_NAME="${TIMESTAMP}-${COMMIT_SHA:0:8}.json"
          
          # Create history directories if they don't exist
          mkdir -p benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/history
          mkdir -p benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/history
          
          # Archive current benchmark data if it exists
          if [ -f "benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/data/benchmark-data.json" ]; then
            cp benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/data/benchmark-data.json \
               "benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/history/${ARCHIVE_NAME}"
          fi
          
          if [ -f "benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/data/benchmark-data.json" ]; then
            cp benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/data/benchmark-data.json \
               "benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/history/${ARCHIVE_NAME}"
          fi

      - name: Fetch Previous History
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: cuioss/cuioss.github.io
          ref: main
          path: previous-pages
          sparse-checkout: |
            cui-jwt/benchmarks/micro/history
            cui-jwt/benchmarks/integration/history
        continue-on-error: true
        
      - name: Merge Historical Data
        run: |
          # Copy previous history if it exists
          if [ -d "previous-pages/cui-jwt/benchmarks/micro/history" ]; then
            echo "📜 Merging micro benchmark history..."
            mkdir -p benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/history
            cp -n previous-pages/cui-jwt/benchmarks/micro/history/*.json \
               benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/history/ 2>/dev/null || true
          fi
          
          if [ -d "previous-pages/cui-jwt/benchmarks/integration/history" ]; then
            echo "📜 Merging integration benchmark history..."
            mkdir -p benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/history
            cp -n previous-pages/cui-jwt/benchmarks/integration/history/*.json \
               benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/history/ 2>/dev/null || true
          fi
          
          # Enforce retention policy (keep only 10 most recent)
          for dir in benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/history \
                     benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/history; do
            if [ -d "$dir" ]; then
              echo "🧹 Enforcing retention policy in $dir"
              cd "$dir"
              ls -t *.json 2>/dev/null | tail -n +11 | xargs rm -f 2>/dev/null || true
              cd - > /dev/null
            fi
          done

      - name: Combine Benchmark Artifacts
        run: |
          # Create combined gh-pages directory with separate subdirectories for each benchmark type
          mkdir -p gh-pages
          mkdir -p gh-pages/micro
          mkdir -p gh-pages/integration
          mkdir -p gh-pages/badges
          
          # Copy micro benchmark artifacts to micro subdirectory
          if [ -d "benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready" ]; then
            echo "📦 Copying micro benchmark artifacts..."
            cp -r benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/* gh-pages/micro/
            # Copy micro badges to root badges directory
            if [ -d "benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/badges" ]; then
              cp benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/badges/performance-badge.json gh-pages/badges/ 2>/dev/null || true
              cp benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/badges/trend-badge.json gh-pages/badges/ 2>/dev/null || true
              cp benchmarking/benchmark-library/target/benchmark-results/gh-pages-ready/badges/last-run-badge.json gh-pages/badges/ 2>/dev/null || true
            fi
          fi
          
          # Copy integration benchmark artifacts to integration subdirectory
          if [ -d "benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready" ]; then
            echo "📦 Copying integration benchmark artifacts..."
            cp -r benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/* gh-pages/integration/
            # Copy integration badges to root badges directory
            if [ -d "benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/badges" ]; then
              cp benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/badges/performance-badge.json gh-pages/badges/integration-performance-badge.json 2>/dev/null || true
              cp benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/badges/trend-badge.json gh-pages/badges/integration-trend-badge.json 2>/dev/null || true
              cp benchmarking/benchmark-integration-quarkus/target/benchmark-results/gh-pages-ready/badges/last-run-badge.json gh-pages/badges/integration-last-run-badge.json 2>/dev/null || true
            fi
          fi
          
          # Add metadata
          echo "{ \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"commit\": \"${{ github.sha }}\" }" > gh-pages/metadata.json
          
          echo "📊 Combined artifacts structure:"
          ls -la gh-pages/
          echo "📊 Micro history:"
          ls -la gh-pages/micro/history/ 2>/dev/null || echo "No micro history"
          echo "📊 Integration history:"
          ls -la gh-pages/integration/history/ 2>/dev/null || echo "No integration history"
          
      - name: Upload benchmark results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: benchmark-results
          path: gh-pages/
          retention-days: 90  # Keep results for 90 days

      - name: Deploy to cuioss.github.io
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: gh-pages
          repository-name: cuioss/cuioss.github.io
          target-folder: cui-jwt/benchmarks
          branch: main
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
