# JWT Integration Tests - Docker Compose Configuration
# Purpose: Container-based integration testing for CUI JWT Quarkus extension

services:
  cui-jwt-integration-tests:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
      # Build optimization settings
      cache_from:
        - quay.io/quarkus/quarkus-distroless-image:2.0
      platforms:
        - linux/amd64
        - linux/arm64
    
    ports:
      - "10443:8443"  # External test port for integration tests
    
    volumes:
      - ./src/main/docker/certificates:/app/certificates:ro
    
    environment:
      - QUARKUS_PROFILE=integration
      - QUARKUS_LOG_LEVEL=INFO
      - QUARKUS_HTTP_SSL_CERTIFICATE_KEY_STORE_FILE=/app/certificates/keystore.p12
      - QUARKUS_HTTP_SSL_CERTIFICATE_KEY_STORE_PASSWORD=integration-test
    
    # OWASP Security hardening for integration testing
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /app/tmp:rw,noexec,nosuid,size=50m
    
    # Resource limits for testing consistency
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
    
    # Health check for integration test validation
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - jwt-integration

networks:
  jwt-integration:
    driver: bridge